name: Auto-Pilot Match Fetcher

on:
schedule:
    - cron: '30 0,7,12 * * *' # यह रोज़ सुबह 6:00, दोपहर 1:00, और शाम 6:00 बजे (IST) चलेगा
  workflow_dispatch: # यह आपको कभी भी बटन दबाकर (Manual) चलाने की सुविधा देता है

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install libraries
        run: pip install -r requirements.txt

      - name: Run Auto-Pilot Code
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          SPORTS_API_KEY: ${{ secrets.SPORTS_API_KEY }}
        run: python main.py
